[[redirects]]
  from = "/notes/"
  to = "https://publish.obsidian.md/bearlythinking/:splat"
  status = 200
  force = true

# Put all other redirects/rewrites above this line
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
